"""Change rating table names

Revision ID: aaa9cb5c1d0a
Revises: 5639cc58cc63
Create Date: 2025-04-14 15:10:29.996517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aaa9cb5c1d0a'
down_revision: Union[str, None] = '5639cc58cc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'book', 'category', ['category_id'], ['id'])
    op.add_column('review', sa.Column('rating_star', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('review', 'rating_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating_start', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('review', 'rating_star')
    op.drop_constraint(None, 'book', type_='foreignkey')
    # ### end Alembic commands ###
