"""change rating

Revision ID: e795caf91add
Revises: 41c5d3716806
Create Date: 2025-04-25 11:05:02.891911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e795caf91add'
down_revision: Union[str, None] = '41c5d3716806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE review ALTER COLUMN rating_star TYPE INTEGER USING rating_star::INTEGER")
    op.alter_column('review', 'rating_star',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE review ALTER COLUMN rating_star TYPE VARCHAR USING rating_star::TEXT")
    op.alter_column('review', 'rating_star',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
